"""Tcl script generator for OpenROAD initialize_floorplan (ifp).

Reference: https://openroad.readthedocs.io/en/latest/main/src/ifp/README.html

initialize_floorplan supports exactly two sizing modes — this generator
enforces mutual exclusivity at the Python level before emitting any Tcl.

Mode A — explicit die/core area:
    initialize_floorplan
        -die_area  {llx lly urx ury}
        -core_area {llx lly urx ury}
        -site      <site_name>

Mode B — utilization + aspect ratio + core_space:
    initialize_floorplan
        -utilization   <float>
        -aspect_ratio  <float>
        -core_space    {left bottom right top}
        -site          <site_name>
"""
from __future__ import annotations

from pathlib import Path
from typing import List, Optional, Tuple

from src.data.benchmark_base import BenchmarkDesign, SizingMode


class IFPTclGenerator:
    """Generates a complete OpenROAD Tcl script that calls initialize_floorplan."""

    def __init__(
        self,
        design: BenchmarkDesign,
        output_def: Path,
        additional_sites: Optional[List[str]] = None,
        flip_sites: bool = False,
        row_parity: Optional[str] = None,   # "even" | "odd" | None
        make_tracks: bool = True,
        track_layers: Optional[List[dict]] = None,
        extra_tcl: str = "",
    ) -> None:
        design.validate_sizing()
        self.design         = design
        self.output_def     = output_def
        self.additional_sites = additional_sites or []
        self.flip_sites     = flip_sites
        self.row_parity     = row_parity
        self.make_tracks    = make_tracks
        self.track_layers   = track_layers or []
        self.extra_tcl      = extra_tcl

    # ── public ───────────────────────────────────────────────────────────────

    def generate(self) -> str:
        """Return the complete Tcl script as a string."""
        d = self.design
        lines: List[str] = []

        lines += self._header()
        lines += self._read_lef()
        lines += self._read_def()
        lines += self._initialize_floorplan()
        if self.additional_sites or self.flip_sites or self.row_parity:
            lines += self._make_rows()
        if self.make_tracks and self.track_layers:
            lines += self._make_tracks()
        if self.extra_tcl:
            lines.append(self.extra_tcl)
        lines += self._write_def()
        lines += self._footer()

        return "\n".join(lines) + "\n"

    def write(self, path: Path) -> None:
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(self.generate())

    # ── private builders ─────────────────────────────────────────────────────

    def _header(self) -> List[str]:
        return [
            "# Auto-generated by CA-Floorplanner IFPTclGenerator",
            f"# Design : {self.design.name}",
            f"# Family : {self.design.family}",
            f"# Sizing : {self.design.sizing_mode.value}",
            "",
        ]

    def _read_lef(self) -> List[str]:
        d = self.design
        if not d.lef_path:
            return ["# No LEF specified; assuming already loaded in DB"]
        return [f"read_lef {d.lef_path}", ""]

    def _read_def(self) -> List[str]:
        d = self.design
        if not d.def_path:
            return ["# No input DEF specified; starting from empty DB"]
        return [f"read_def {d.def_path}", ""]

    def _initialize_floorplan(self) -> List[str]:
        d = self.design
        site = d.site
        lines: List[str] = ["# ── initialize_floorplan ──────────────────────────"]

        if d.sizing_mode == SizingMode.DIE_CORE:
            # Mode A: explicit die/core area
            # Must NOT include utilization or aspect_ratio
            da = " ".join(str(v) for v in d.die_area)
            ca = " ".join(str(v) for v in d.core_area)
            lines += [
                "initialize_floorplan \\",
                f"    -die_area  {{ {da} }} \\",
                f"    -core_area {{ {ca} }} \\",
                f"    -site      {site}",
                "",
            ]
        else:
            # Mode B: utilization + aspect_ratio + core_space
            # Must NOT include die_area or core_area
            cs = " ".join(str(v) for v in d.core_space)
            lines += [
                "initialize_floorplan \\",
                f"    -utilization   {d.utilization:.4f} \\",
                f"    -aspect_ratio  {d.aspect_ratio:.4f} \\",
                f"    -core_space    {{ {cs} }} \\",
                f"    -site          {site}",
                "",
            ]

        return lines

    def _make_rows(self) -> List[str]:
        """Emit make_rows for hybrid-row or additional-site configurations."""
        d = self.design
        lines = ["# ── make_rows (additional sites / parity) ───────────────"]
        args = [f"-site {d.site}"]
        for s in self.additional_sites:
            args.append(f"-additional_sites {s}")
        if self.flip_sites:
            args.append("-flip_alternate_rows")
        if self.row_parity:
            args.append(f"-row_parity {self.row_parity}")
        lines.append("make_rows " + " ".join(args))
        lines.append("")
        return lines

    def _make_tracks(self) -> List[str]:
        lines = ["# ── make_tracks ──────────────────────────────────────────"]
        for t in self.track_layers:
            layer   = t.get("layer", "M1")
            x_off   = t.get("x_offset", 0)
            x_pitch = t.get("x_pitch", 0.1)
            y_off   = t.get("y_offset", 0)
            y_pitch = t.get("y_pitch", 0.1)
            lines.append(
                f"make_tracks {layer} "
                f"-x_offset {x_off} -x_pitch {x_pitch} "
                f"-y_offset {y_off} -y_pitch {y_pitch}"
            )
        lines.append("")
        return lines

    def _write_def(self) -> List[str]:
        return [
            "# ── write result ─────────────────────────────────────────────",
            f"write_def {self.output_def}",
            "",
        ]

    def _footer(self) -> List[str]:
        return ["exit"]
